### ISSUE TITLE
urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>

### ISSUE THREAD

**Issue by gjgetzinger** [mcs07/CIRpy#3]
I recently installed cirpy on mac osx (10.11.1) using pip. I tried the example and got the following: 

> > > cirpy.resolve('Aspirin', 'smiles')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Python/2.7/site-packages/cirpy.py", line 192, in resolve
> > >     results = query(input, representation, resolvers, False, get3d, *_kwargs)
> > >   File "/Library/Python/2.7/site-packages/cirpy.py", line 162, in query
> > >     tree = request(input, representation, resolvers, get3d, tautomers, *_kwargs)
> > >   File "/Library/Python/2.7/site-packages/cirpy.py", line 95, in request
> > >     response = urlopen(url)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
> > >     return opener.open(url, data, timeout)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
> > >     response = self._open(req, data)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
> > >     '_open', req)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
> > >     result = func(*args)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
> > >     context=self._context)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
> > >     raise URLError(err)
> > > urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>

**Comment by mcs07** [comment]
It seems the python that comes pre-installed on OS X uses an ancient version of OpenSSL (0.9.8) that doesn't support TLSv1.2 which is now required since the NCI servers moved over to using https.

In the short term, you could disable SSL by setting the API URL back to http instead of https:

```
>>> import cirpy
>>> cirpy.API_BASE = 'http://cactus.nci.nih.gov/chemical/structure'
>>> cirpy.resolve('aspirin', 'smiles')
'CC(=O)Oc1ccccc1C(O)=O'
```

But this is not a good long term solution, because the NCI say they are turning off http support at the end of March.

A better solution is to install python using [homebrew](http://brew.sh):

```
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
$ brew update
$ brew doctor
$ brew install python
```

This will install a newer version of Python at `/usr/local/bin/python` (compared to the system python at `/usr/bin/python`). You can type `which python` to double-check that when you just type `python` in your Terminal, it find the Homebrew version. The Homebrew python is isolated from the system python, so you'll have to install CIRpy again with `pip install cirpy`.

**Comment by gjgetzinger** [comment]
Thanks for your quick response, Matt. Updating python seems to have done the trick. I had to overwrite the path (brew link —overwrite python) in order to get the correct version to load.

Sorry if this was a trivial question. I’m just getting started in python. Thanks for your time.

Gordon

On Jan 14, 2016, at 6:52 PM, Matt Swain <notifications@github.com<mailto:notifications@github.com>> wrote:

It seems the python that comes pre-installed on OS X uses an ancient version of OpenSSL (0.9.8) that doesn't support TLSv1.2 which is now required since the NCI servers moved over to using https.

In the short term, you could disable SSL by setting the API URL back to http instead of https:

> > > import cirpy
> > > cirpy.API_BASE = 'http://cactus.nci.nih.gov/chemical/structure'
> > > cirpy.resolve('aspirin', 'smiles')
> > > 'CC(=O)Oc1ccccc1C(O)=O'

But this is not a good long term solution, because the NCI say they are turning off http support at the end of March.

A better solution is to install python using homebrewhttp://brew.sh/:

$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
$ brew update
$ brew doctor
$ brew install python

This will install a newer version of Python at /usr/local/bin/python (compared to the system python at /usr/bin/python). You can type which python to double-check that when you just type python in your Terminal, it find the Homebrew version. The Homebrew python is isolated from the system python, so you'll have to install CIRpy again.

**Comment by mcs07** [comment]
I'm glad it worked. It's not a trivial question at all, so thanks for the report.

I will continue to look into whether I can find a workaround to get CIRpy to work with the system python version on Mac OS X, but I don't think there's much I can do. It's either down to Apple to update the OpenSSL version or the NCI to support older SSL versions on their server.

**Comment by mcs07** [comment]
I believe the NCI have re-enabled earlier versions of TLS on their servers, so this problem should no longer occur.
