### ISSUE TITLE
SMILES string full of tungsten 

### ISSUE THREAD

**Issue by jtd1g16** [mcs07/CIRpy#7]
4,4',4''-methanetriyltris(N,N-diethylaniline) (https://pubchem.ncbi.nlm.nih.gov/compound/Leucocrystal-Violet#section=MeSH-Entry-Terms) comes up with the following SMILES:
[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].[W].CCN(CC)c1ccc(cc1)C+c3ccc(cc3)N(CC)CC'

**Comment by khoivan88** [comment]
Probably you already figured it out but I couldn't replicate your issue. Running on mine, it returns:
```python
>>>cirpy.resolve("4,4',4''-methanetriyltris(N,N-diethylaniline)", 'smiles')
'CCN(CC)c1ccc(cc1)C(c2ccc(cc2)N(CC)CC)c3ccc(cc3)N(CC)CC'
```

**Comment by mcs07** [comment]
I also cannot reproduce. Is that the exact input that you used?

**Comment by jtd1g16** [comment]
> I also cannot reproduce. Is that the exact input that you used?

That would have been a direct copy of my input - I just tried and this seems to be resolved!
