### ISSUE TITLE
API Not responding.

### ISSUE THREAD

**Issue by messi313** [mcs07/CIRpy#8]
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

Having the above issue while running this command    
 cirpy.resolve('Aspirin', 'smiles')

**Comment by khoivan88** [comment]
Maybe it was just a down server time? it is working just fine for me now?!

**Comment by mcs07** [comment]
Also working fine for me currently.
